services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/HospitalManagementSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Rohith2005rtg

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"