name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node (Frontend)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          ls
          node -v
          npm -v
          npm ci
          npm run build

      # 4. Setup Java (Backend)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 5. Build Backend
      - name: Build Backend
        run: |
          chmod +x mvnw
          ./mvnw -f backend/pom.xml clean package -DskipTests
          

      # 6. Build Docker images
      - name: Build Docker images
        run: docker compose build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
              host: ${{ secrets.EC2_HOST }}
              username: ubuntu
              key: ${{ secrets.EC2_SSH_KEY }}
              script: |
                cd HospitalManagementSystem
                git pull origin main
                docker-compose down
                docker-compose up -d --build

