name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- BACKEND ----------------
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend
        run: |
          cd backend
          mvn clean install -DskipTests

      # ---------------- FRONTEND ----------------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # ---------------- DOCKER ----------------
      - name: Build Docker images
        run: docker-compose build